Web_Lk_Xe/Controllers/DanhMucSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Lk_Xe.Models;

namespace Web_Lk_Xe.Controllers
{
    public class DanhMucSPController : Controller
    {
        Data_LKXeDataContext dl = new Data_LKXeDataContext();
       
        // GET: DanhMuSanPham
        public ActionResult DanhMucSanPham()
        {
            List<LOAISP> dsDM = dl.LOAISPs.ToList();
            return PartialView(dsDM);
        }
    }
}

Web_Lk_Xe/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Lk_Xe.Models;
namespace Web_Lk_Xe.Controllers
{
    public class  UserController : Controller
    {
        Data_LKXeDataContext dl = new Data_LKXeDataContext();
        // GET: User
        public ActionResult Account()
        {
            return View();
        }
        [HttpPost]
        public JsonResult createAccount(string tenTk, string pass, string tkh)
        {
          
            TAIKHOAN checkTk = dl.TAIKHOANs.FirstOrDefault(t => t.TENDN == tenTk);
            if (checkTk != null)
            {
                return Json(new { code = 200, msg = "Đăng ký thất bại, Tài khoản đã tồn tại" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                KHACHHANG kh = new KHACHHANG();
                TAIKHOAN tk = new TAIKHOAN();
                tk.TENDN = tenTk;
                tk.PASS = pass;
                tk.LOAITK = "KhachHang";
                dl.TAIKHOANs.InsertOnSubmit(tk);
                kh.MAKH = "";
                kh.TENKH = tkh;
                kh.TENDN = tenTk;
                dl.KHACHHANGs.InsertOnSubmit(kh);
                dl.SubmitChanges();
                return Json(new {code =500, msg = "Đăng ký thành công" }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public JsonResult loginAccount(string tenTk, string pass)
        {
            TAIKHOAN checkdn = dl.TAIKHOANs.FirstOrDefault(t => t.TENDN == tenTk && t.PASS == pass);
            
            
            if (checkdn != null)
            {
                Session["ttDangNhap"] = checkdn;
                KHACHHANG chechkh = dl.KHACHHANGs.FirstOrDefault(t => t.TENDN == checkdn.TENDN);
                Session["ttkh"] = chechkh;


                // Lay so luong san pham co trong gio khach hang dang nhap
                List<GIOHANG> ghKDN = dl.GIOHANGs.Where(t => t.MAKH == chechkh.MAKH).ToList();
                
                Session["gh_DangNhap"] = ghKDN.Count();

             

                return Json(new { code = 500, msg = "Đăng nhập thành công" }, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json(new { code = 200, msg = "Đăng nhập thất bại"}, JsonRequestBehavior.AllowGet);

            }
        }

        // Hien thi me menu tai khoan
        public ActionResult menuAccount()
        {
            KHACHHANG s = (KHACHHANG)Session["ttkh"];
            TAIKHOAN a = dl.TAIKHOANs.FirstOrDefault(t => t.TENDN == s.TENDN);
            return PartialView(a);
        }


        // Cap nhat thong tin tai khoan
        public ActionResult capNhatTtAccount()
        {
            return View();
        }

        //Load du lieu
       [HttpGet]
        public JsonResult loadTtAccount()
        {
            try
            {
                KHACHHANG kh = (KHACHHANG)Session["ttkh"];
                KHACHHANG khs;
                khs = dl.KHACHHANGs.FirstOrDefault(t => t.MAKH == kh.MAKH);

                return Json(new
                {
                    code = 500,
                    tenkh = khs.TENKH,
                    Email = khs.TENDN,
                    sdt = khs.SDT,
                    gt = khs.GIOTINH,

                    msg = "Load thông tin thành công"
                }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { code = 200, msg = "Load thông tin thất bại" }, JsonRequestBehavior.AllowGet);

            }




        }


        [HttpPost]
        public JsonResult XlcapNhatAccount(string tenkh, string sdt, string gt)
        {
            try
            {
                KHACHHANG kh = (KHACHHANG)Session["ttkh"];
                KHACHHANG khs = new KHACHHANG();
                khs = dl.KHACHHANGs.FirstOrDefault(t => t.MAKH == kh.MAKH);
                if(khs != null)
                {
                    khs.TENKH = tenkh;
                    khs.SDT = sdt;
                    khs.GIOTINH = gt;
                    dl.SubmitChanges();
                }
                Session["ttkh"] = khs;
                return Json(new { code = 500, msg = "Cập nhật tài khoản thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { code = 200, msg = "Cập nhật tài khoản thất bại" }, JsonRequestBehavior.AllowGet);

            }
        }
        [HttpPost]
        public JsonResult xlDoiPass(string PassOld, string PassNew)
        {
            TAIKHOAN tkcheck = (TAIKHOAN)Session["ttDangNhap"];
            if(PassOld == tkcheck.PASS)
            {
                TAIKHOAN doiPass = new TAIKHOAN();
                doiPass = dl.TAIKHOANs.FirstOrDefault(t => t.TENDN == tkcheck.TENDN);
                doiPass.PASS = PassNew;
                dl.SubmitChanges();
                return Json(new { code = 500, msg = "Cập nhật mật khẩu mới thành công" }, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json(new { code = 200, msg = "Mật khẩu cũ không đúng" }, JsonRequestBehavior.AllowGet);

            }
        }

        
        public ActionResult XemDonHang()
        {
            return View();
        }



        public ActionResult DangXuat()
        {
           Session.Clear();
           return RedirectToAction("Index", "Home");
        }
    }
}

Web_Lk_Xe/Views/Shared/Admin_Page.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <!-- gg font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <link href="~/Assces/AdminPage.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="grid-container">

        <!-- Header -->
        <header class="header">
            <div class="menu-icon" onclick="openSidebar()">
                <span class="material-icons-outlined">menu</span>
            </div>
            <div class="header-left">
                <span class="material-icons-outlined">search</span>
            </div>
            <div class="header-right">
                <span class="material-icons-outlined">notifications</span>
                <span class="material-icons-outlined">email</span>
                <span class="material-icons-outlined">account_circle</span>
            </div>
        </header>
        <!-- End Header -->
        <!-- Sidebar -->
        <aside id="sidebar">
            <div class="sidebar-title">
                <div class="sidebar-brand">
                    <span class="material-icons-outlined">inventory</span> ADMIN
                </div>
                <span class="material-icons-outlined" onclick="closeSidebar()">close</span>
            </div>

            <ul class="sidebar-list">
                <li class="sidebar-list-item">
                    <a href="#" target="_blank">
                        <span class="material-icons-outlined">dashboard</span> Dashboard
                    </a>
                </li>
                <li class="sidebar-list-item">
                    <a href="/Admin/QLSanPham">
                        <span class="material-icons-outlined">inventory_2</span> Quản Lý Sản Phẩm
                    </a>
                </li>
                <li class="sidebar-list-item">
                    <a href="/Admin/QLHoaDon">
                        <span class="material-icons-outlined">fact_check</span> Quản Lý Hóa Đơn
                    </a>
                </li>
                <li class="sidebar-list-item">
                    <a href="/Admin/QLKhachHang" target="_blank">
                        <span class="material-icons-outlined">shopping_cart</span> Quản Lý Khách Hàng
                    </a>
                </li>
                
            </ul>
        </aside>
        <!-- End Sidebar -->
        <!-- Main -->
        <main class="main-container">
            @*<div class="main-title">
                <p class="font-weight-bold">DASHBOARD</p>
            </div>

            <div class="main-cards">

                <div class="card">
                    <div class="card-inner">
                        <p class="text-primary">PRODUCTS</p>
                        <span class="material-icons-outlined text-blue">inventory_2</span>
                    </div>
                    <span class="text-primary font-weight-bold">249</span>
                </div>

                <div class="card">
                    <div class="card-inner">
                        <p class="text-primary">PURCHASE ORDERS</p>
                        <span class="material-icons-outlined text-orange">add_shopping_cart</span>
                    </div>
                    <span class="text-primary font-weight-bold">83</span>
                </div>

                <div class="card">
                    <div class="card-inner">
                        <p class="text-primary">SALES ORDERS</p>
                        <span class="material-icons-outlined text-green">shopping_cart</span>
                    </div>
                    <span class="text-primary font-weight-bold">79</span>
                </div>

                <div class="card">
                    <div class="card-inner">
                        <p class="text-primary">INVENTORY ALERTS</p>
                        <span class="material-icons-outlined text-red">notification_important</span>
                    </div>
                    <span class="text-primary font-weight-bold">56</span>
                </div>

            </div>

            <div class="charts">

                <div class="charts-card">
                    <p class="chart-title">Top 5 Products</p>
                    <div id="bar-chart"></div>
                </div>

                <div class="charts-card">
                    <p class="chart-title">Purchase and Sales Orders</p>
                    <div id="area-chart"></div>
                </div>

            </div>*@
             @RenderBody()
        </main>
        <!-- End Main -->
       

    </div>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.35.3/apexcharts.min.js"></script>
    <script src="~/Assces/Admin.js"></script>
</body>


</html>

Web_Lk_Xe/Views/Shared/LayoutPage.cshtml
@using Web_Lk_Xe.Models

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    @*Thu vien slick*@
    <link href="~/Assces/ThuVien/slick-1.8.1/slick/slick.css" rel="stylesheet" />
    <link href="~/Assces/ThuVien/slick-1.8.1/slick/slick-theme.css" rel="stylesheet" />
    @*css LayoutPage*@
    <link href="~/Assces/LayoutPage.css" rel="stylesheet" />
    <!-- Icon -->
    <link href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css" rel="stylesheet">
    <script src="~/Assces/ThuVien/bootstrap5_2_3/js/bootstrap.bundle.js"></script>
    <script src="~/Assces/ThuVien/bootstrap5_2_3/js/bootstrap.js"></script>
    <link href="~/Assces/ThuVien/bootstrap5_2_3/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Assces/ThuVien/bootstrap5_2_3/css/bootstrap.min.css" rel="stylesheet" />
    <!-- gg font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="main-body">


        <!-- Header - menu -->

        <div class="header">
            <div class="container">
                <div class="header-wrap">
                    <div class="header-logo">
                        <img class="header_img" src="~/Assces/Anh/Logo/z4015898930397_319843a1f665832094da45e62c2b01da.png" />
                    </div>
                    <div class="header-menu">
                        <ul class="nav_menu">
                            <li class="nav_menu-item"><a href="" class="nav_menu-link" style="font-size: 20px; display: flex;align-items: center;"><i class='bx bx-search-alt-2'></i></a></li>
                            <li class="nav_menu-item"><a href="/Home/Index" class="nav_menu-link">trang chủ</a></li>
                            <li class="nav_menu-item nav_sub-menu">
                                <a href="#" class="nav_menu-link" style="display: flex; align-items: center;">
                                    Sản phẩm
                                    <i class='bx bx-chevron-down icon_d' style="font-size: 20px;"></i>
                                </a>
                                @Html.Action("DanhMucSanPham", "DanhMucSP")

                            </li>
                            <li class="nav_menu-item"><a href="" class="nav_menu-link">giới thiệu</a></li>
                            <li class="nav_menu-item"><a href="" class="nav_menu-link">liên hệ</a></li>
                        </ul>
                    </div>

                    <div class="header_function">
                        <ul class="nav_function">
                            <li class="nav_function-item">
                                <a href="/GioHang/xemCtGio" class="nav_function-link" style="display: flex; align-items: center; position: relative">
                                    <span>
                                        Giỏ hàng

                                    </span>
                                    <div class="cart-icon" style=" display: flex; align-items: center; margin-left: 6px; ">
                                        <i class="bx bx-cart" style="font-size: 20px"></i>
                                    </div>
                                    @*Hien thi gio hang*@
                                    @{
                                        // neu dang nhap thi hien gio duoi csdl
                                        if (Session["ttDangNhap"] != null)
                                        {

                                            <span class="cart-count" id="addcart">
                                                @Session["gh_DangNhap"].ToString()
                                            </span>

                                        }
                                        else
                                        {
                                            if (Session["CART"] != null)
                                            {
                                                gioHang gh = (gioHang)Session["CART"];
                                                <span class="cart-count" id="addcart">
                                                    @gh.DemSL()
                                                </span>

                                            }
                                            else
                                            {
                                                <span class="cart-count" id="addcart">
                                                    0
                                                </span>
                                            }
                                        }

                                    }
                                </a>
                            </li>
                            <li class="nav_function-item nav_sub-menu">
                                @{
                                    if (Session["ttDangNhap"] == null)
                                    {
                                        <a href="/User/Account" class="nav_function-link">
                                            <span>
                                                Đăng nhập
                                            </span>
                                        </a>
                                    }
                                    else
                                    {
                                        KHACHHANG dnkh = (KHACHHANG)Session["ttkh"];
                                        
                                        <a href="#" class="nav_function-link">
                                            <span id="tenkh_add">
                                                @dnkh.TENKH
                                            </span>

                                        </a>
                                        @Html.Action("menuAccount", "User")

                                    }
                                }

                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <!-- End - menu -->

        <div>
            @RenderBody()
        </div>

        <div class="footer-main">
            <div class="footer-content">
                <div class="container">
                    <div class="row ">
                        <div class="col-md-3 footer-lion">
                            <h4 class="title-footer">PHỤ KIỆN</h4>
                            <div class="row footer-content-lion">
                                <div class="col-md footer-content-lion-text">
                                    <p>
                                        Đưa đến một chất lượng sản phẩm hoàn hảo với một giá thành hợp lí nhất. Luôn đặt
                                        khách hàng lên trên cả lợi nhuận.
                                    </p>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-3 footer-lion">
                            <h4 class="title-footer">Hỗ trợ khách hàng</h4>
                            <div class="footer-content-lion">
                                <ul class="footer-Navlink">
                                    <li><a href="./GioiThieu.html">Giới thiệu</a></li>
                                    <li><a href="./ChinhSachDoiTra.html">Chính sách đổi trả</a></li>
                                    <li><a href="./ChinhSachBaoMat.html">Chính sách bảo mật</a></li>
                                </ul>

                            </div>
                        </div>
                        <div class="col-md-3 footer-lion">
                            <h4 class="title-footer">Liên Hệ </h4>
                            <div class="footer-lion-content">
                                <div class="footer-infor">
                                    <span>
                                        <b style="color: #fff !important;">Địa chỉ:</b> 400 Tân Kỳ Tân Quý, Phường
                                        Sơn Kỳ, Quận Tân Phú, Tp Hồ Chí Minh
                                    </span>
                                    <ul class="add-footer-content-lion">
                                        <li><b style="color: #fff;">Điện Thoại: </b>0366178160</li>
                                        <li><b style="color: #fff;">Email: </b>likonTeam123@gmail.com</li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-3 footer-lion">
                            <div class="flo-me">
                                <h4 class="title-footer " style="color: #fff !important;">Follow PHỤ KIỆN nha! </h4>
                                <ul class="nav footer-nav-icon">
                                    <li>
                                        <a href="" title="Follow on facebook">
                                            <i class="bx bxl-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="" title="Follow on instagram">
                                            <i class="bx bxl-instagram-alt"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="" title="Follow on twitter">
                                            <i class="bx bxl-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="" title="Follow on google">
                                            <i class="bx bxl-google"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <hr style="margin: 0px;">
            <div class="footer-copyright">
                Copyright © 2022 Nhóm 03
            </div>

        </div>



    </div>

    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/Assces/ThuVien/slick-1.8.1/slick/slick.min.js"></script>

    <script>

        $(document).ready(function () {
            $('.slider').slick({
                infinite: true,
                autoplay: true,
                autoplaySpeed: 900,
            });

        });




    </script>


</body>
</html>

Web_Lk_Xe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>